[package]
name = "iceberg-rs"
version = "0.1.1-beta.0"
authors = ["Oliver Daff <oliverdaff@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "An implementation of Apache Iceberg in Rust"
homepage = "https://github.com/oliverdaff/iceberg-rs"
repository = "https://github.com/oliverdaff/iceberg-rs"
keywords = ["iceberg", "analytics", "data"]
categories = ["database", "filesystem"]
include = ["src/**/*.rs", "crates-io.md", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
readme = "crates-io.md"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
regex = "1.5.5"
lazy_static = "1.4.0"
object_store = "0.5.2"
apache-avro = "0.14.0"
serde_bytes = "0.11.7"
anyhow = "1.0"
chrono = { version = "0.4.19", features = ["serde"] }
serde_repr = "0.1"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
anyhow = "1.0"
proptest = "1.0"
